theme: jekyll-theme-chirpy

lang: en
timezone: "America/New_York"

title: Pietro Di Leo
tagline: Data & Finance Builder
description: >-
  blog, dlpietro, github

url: "https://dlpietro.github.io"

github:
  username: DLPietro

twitter:
  username: twitter_username

social:
  name: Pietro Di Leo
  email: dileopie@gmail.com
  links:
    - https://github.com/DLPietro
    - https://www.linkedin.com/in/pietrodileo

# Site Verification Settings
webmaster_verifications:
  google: ""
  bing: ""
  alexa: ""
  yandex: ""
  baidu: ""
  facebook: ""

# Web Analytics Settings
analytics:
  google:
    id: ""  # Fill in your Google Analytics ID
  goatcounter:
    id: ""  # Fill in your GoatCounter ID
  umami:
    id: ""  # Fill in your Umami ID
    domain: ""  # Fill in your Umami domain
  matomo:
    id: ""  # Fill in your Matomo ID
    domain: ""  # Fill in your Matomo domain
  cloudflare:
    id: ""  # Fill in your Cloudflare Web Analytics token
  fathom:
    id: ""  # Fill in your Fathom Site ID

# Page views settings
pageviews:
  provider: goatcounter  # Adjust this if needed

# Prefer color scheme setting
theme_mode: dark  # Choose "light" or "dark"

# CDN endpoint for media resources
cdn: ""

# Avatar for the sidebar
avatar: https://leviarista.github.io/github-profile-header-generator/images/decorations/terminal-circle.png

# The URL of the site-wide social preview image used in SEO `og:image` meta tag
social_preview_image: "/assets/images/social_preview.jpg"  # Optional

# Boolean for the TOC in posts
toc: true

comments:
  provider: disqus  # Choose a comment provider, e.g., disqus, utterances, giscus
  disqus:
    shortname: "your-disqus-shortname"  # Fill with your Disqus shortname

# PWA settings
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:
      - "/example"  # URLs matching <SITE_URL>/example/* will not be cached by the PWA

paginate: 10

# The base URL of your site
baseurl: "/"

# kramdown configuration for footnotes and syntax highlighting
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Collections for tabs
collections:
  tabs:
    output: true
    sort_by: order

# Defaults for post layout and permalink
defaults:
  - scope:
      path: ""  # An empty string means all files
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

# Sass configuration
sass:
  style: compressed

# HTML compression
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# Exclude unnecessary files and directories
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

# jekyll-archives configuration
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
